// Control descriptors for the lab panel; each entry's flags tell the pond which side effect a change needs.
import { BRUSHES } from './presets.js';

export var SCHEMA = {
  shape: [
    { k: 'kind', l: 'Animal', t: 'select', o: ['fish', 'swallow'], paint: true },
    { k: 'variety', l: 'Variety', t: 'range', min: 0, max: 1, step: 0.05, paint: true, tip: 'per-variant jitter of proportions' },
    { k: 'len', l: 'Length', t: 'range', min: 120, max: 320, step: 2, paint: true },
    { k: 'height', l: 'Height / span', t: 'range', min: 30, max: 300, step: 2, paint: true },
    { k: 'curvature', l: 'Roundness', t: 'range', min: 0, max: 1, step: 0.05, paint: true },
    { k: 'dorsal', l: 'Dorsal fin', t: 'range', min: 0, max: 80, step: 1, paint: true },
    { k: 'tailLen', l: 'Tail length', t: 'range', min: 10, max: 90, step: 1, paint: true },
    { k: 'tailSpread', l: 'Tail spread', t: 'range', min: 10, max: 120, step: 1, paint: true },
    { k: 'tailBend', l: 'Pose bend', t: 'range', min: 0, max: 40, step: 1, paint: true, tip: 'only used by the painted-poses animation' },
  ],
  paint: [
    { k: 'brushScale', l: 'Brush scale', t: 'range', min: 1, max: 6, step: 0.25, paint: true },
    { k: 'seed', l: 'Seed', t: 'range', min: 0, max: 99, step: 1, paint: true },
    { sub: 'Wash' },
    { k: 'washOn', l: 'Body wash', t: 'bool', paint: true },
    { k: 'washOpacity', l: 'Opacity', t: 'range', min: 20, max: 255, step: 5, paint: true },
    { k: 'bleed', l: 'Bleed', t: 'range', min: 0, max: 1, step: 0.02, paint: true },
    { k: 'bleedDir', l: 'Bleed dir', t: 'select', o: ['out', 'in'], paint: true },
    { k: 'texture', l: 'Texture', t: 'range', min: 0, max: 1, step: 0.05, paint: true },
    { k: 'border', l: 'Edge darkening', t: 'range', min: 0, max: 1, step: 0.05, paint: true },
    { k: 'scatter', l: 'Edge scatter', t: 'bool', paint: true },
    { k: 'glazeOn', l: 'Back glaze', t: 'bool', paint: true },
    { k: 'glazeOpacity', l: 'Glaze opacity', t: 'range', min: 10, max: 200, step: 5, paint: true },
    { k: 'glazeBleed', l: 'Glaze bleed', t: 'range', min: 0, max: 1, step: 0.02, paint: true },
    { sub: 'Markings' },
    { k: 'markingsOn', l: 'Markings', t: 'bool', paint: true },
    { k: 'markOpacity', l: 'Opacity', t: 'range', min: 30, max: 255, step: 5, paint: true },
    { k: 'markBleed', l: 'Bleed', t: 'range', min: 0, max: 1, step: 0.02, paint: true },
    { k: 'markScale', l: 'Patch size', t: 'range', min: 0.4, max: 2, step: 0.05, paint: true },
    { k: 'markDensity', l: 'Patch count', t: 'range', min: 0.3, max: 2.5, step: 0.1, paint: true },
    { sub: 'Line' },
    { k: 'outlineOn', l: 'Outline', t: 'bool', paint: true },
    { k: 'outlineBrush', l: 'Brush', t: 'select', o: BRUSHES, paint: true },
    { k: 'outlineWeight', l: 'Weight', t: 'range', min: 0.3, max: 3, step: 0.05, paint: true },
    { k: 'wiggle', l: 'Hand wobble', t: 'range', min: 0, max: 8, step: 0.5, paint: true },
    { k: 'finsOn', l: 'Fin strokes', t: 'bool', paint: true },
    { k: 'lineOn', l: 'Lateral line', t: 'bool', paint: true },
    { k: 'eyeOn', l: 'Eye', t: 'bool', paint: true },
    { k: 'eyeSize', l: 'Eye size', t: 'range', min: 1, max: 10, step: 0.5, paint: true },
    { sub: 'Hatch' },
    { k: 'hatchOn', l: 'Hatching', t: 'bool', paint: true },
    { k: 'hatchRegion', l: 'Region', t: 'select', o: ['tail', 'body', 'back'], paint: true },
    { k: 'hatchBrush', l: 'Brush', t: 'select', o: BRUSHES, paint: true },
    { k: 'hatchWeight', l: 'Weight', t: 'range', min: 0.2, max: 2, step: 0.05, paint: true },
    { k: 'hatchDist', l: 'Spacing', t: 'range', min: 2, max: 20, step: 0.5, paint: true },
    { k: 'hatchAngle', l: 'Angle', t: 'range', min: -90, max: 90, step: 1, paint: true },
    { k: 'hatchRand', l: 'Randomness', t: 'range', min: 0, max: 1, step: 0.05, paint: true },
  ],
  school: [
    { k: 'count', l: 'Count', t: 'range', min: 1, max: 120, step: 1 },
    { k: 'sizeMin', l: 'Smallest (px)', t: 'range', min: 20, max: 200, step: 2 },
    { k: 'sizeMax', l: 'Largest (px)', t: 'range', min: 20, max: 300, step: 2 },
    { k: 'speed', l: 'Speed', t: 'range', min: 5, max: 200, step: 1 },
    { k: 'turnRate', l: 'Turn rate', t: 'range', min: 0.3, max: 8, step: 0.1 },
    { sub: 'Flocking' },
    { k: 'neighborRadius', l: 'Sight radius', t: 'range', min: 20, max: 400, step: 5 },
    { k: 'separationRadius', l: 'Personal space', t: 'range', min: 5, max: 150, step: 1 },
    { k: 'cohesion', l: 'Cohesion', t: 'range', min: 0, max: 2, step: 0.05 },
    { k: 'alignment', l: 'Alignment', t: 'range', min: 0, max: 300, step: 5 },
    { k: 'separation', l: 'Separation', t: 'range', min: 0, max: 10000, step: 100 },
    { k: 'wander', l: 'Wander', t: 'range', min: 0, max: 150, step: 1 },
    { sub: 'Space' },
    { k: 'roam', l: 'Roaming target', t: 'bool' },
    { k: 'roamPull', l: 'Target pull', t: 'range', min: 0, max: 0.3, step: 0.005 },
    { k: 'edgeMode', l: 'Edges', t: 'select', o: ['walls', 'wrap'] },
    { k: 'edgeMargin', l: 'Wall margin', t: 'range', min: 0, max: 300, step: 5 },
  ],
  motion: [
    { k: 'animMode', l: 'Animation', t: 'select', o: ['spine', 'poses'], paint: true, tip: 'spine: warp one painting along a body wave · poses: three painted tail/wing positions' },
    { k: 'tailHz', l: 'Beat rate', t: 'range', min: 0.2, max: 8, step: 0.1 },
    { k: 'motionVariety', l: 'Variety', t: 'range', min: 0, max: 1, step: 0.05, tip: 'per-fish jitter of beat, amplitude, wavelength' },
    { sub: 'Body wave (spine)' },
    { k: 'waveAmp', l: 'Tail amplitude', t: 'range', min: 0, max: 0.3, step: 0.005 },
    { k: 'headAmp', l: 'Head sway', t: 'range', min: 0, max: 0.1, step: 0.005 },
    { k: 'waveLen', l: 'Wavelength', t: 'range', min: 0.4, max: 2.5, step: 0.05 },
    { k: 'waveProfile', l: 'Stiffness', t: 'range', min: 1, max: 5, step: 0.1, tip: 'higher = only the tail moves' },
    { k: 'turnBend', l: 'Bend into turns', t: 'range', min: 0, max: 1.5, step: 0.05 },
    { sub: 'Burst & coast' },
    { k: 'coastOn', l: 'Coasting', t: 'bool' },
    { k: 'coastEvery', l: 'Burst length (s)', t: 'range', min: 1, max: 20, step: 0.5 },
    { k: 'coastLen', l: 'Coast length (s)', t: 'range', min: 0.3, max: 8, step: 0.1 },
  ],
  book: [
    { k: 'bookOn', l: 'In the journal', t: 'bool', book: 'layout', tip: 'draw the pond on the pages of the journal photo' },
    { k: 'bookZoom', l: 'Zoom', t: 'range', min: 0.5, max: 2.5, step: 0.01, book: 'layout' },
    { k: 'bookX', l: 'Shift x', t: 'range', min: -0.5, max: 0.5, step: 0.005, book: 'layout' },
    { k: 'bookY', l: 'Shift y', t: 'range', min: -0.5, max: 0.5, step: 0.005, book: 'layout' },
    { sub: 'Page mask' },
    { k: 'bookSpineShift', l: 'Spine x shift', t: 'range', min: -60, max: 60, step: 1, book: 'mask', tip: 'photo px from the detected spine' },
    { k: 'bookSpineWidth', l: 'Spine band', t: 'range', min: 0, max: 300, step: 1, book: 'mask', tip: 'width of the strip fish pass under' },
    { k: 'bookSpineSoft', l: 'Spine softness', t: 'range', min: 0, max: 120, step: 1, book: 'mask' },
    { k: 'bookInset', l: 'Page inset', t: 'range', min: -40, max: 80, step: 1, book: 'mask', tip: 'shrink (+) or grow (−) the pages' },
    { k: 'bookFeather', l: 'Edge softness', t: 'range', min: 0, max: 80, step: 1, book: 'mask' },
    { k: 'bookShowMask', l: 'Show mask', t: 'bool', tip: 'tint what the mask hides' },
  ],
  brush: [
    { k: 'bookBrushSize', l: 'Size px', t: 'range', min: 6, max: 400, step: 2 },
    { k: 'bookBrushSoft', l: 'Softness', t: 'range', min: 0, max: 1, step: 0.05 },
  ],
  journal: [
    { k: 'journalOn', l: 'Show journal', t: 'bool', journal: true },
    { k: 'journalX', l: 'Position x', t: 'range', min: 0, max: 1, step: 0.005, journal: true },
    { k: 'journalY', l: 'Position y', t: 'range', min: 0, max: 1, step: 0.005, journal: true },
    { k: 'journalScale', l: 'Size', t: 'range', min: 0.1, max: 1.2, step: 0.005, journal: true },
    { k: 'journalAvoid', l: 'Fish keep away px', t: 'range', min: 0, max: 300, step: 5 },
    { k: 'journalBounce', l: 'Ripples bounce off', t: 'bool' },
  ],
  rock: [
    { k: 'rockOn', l: 'Draw the rock', t: 'bool', rock: true, tip: 'off = the real rock, always' },
    { k: 'rockOnArrows', l: 'Draw the arrows', t: 'bool', rock: true },
    { k: 'rockOnJournal', l: 'Draw the journal', t: 'bool', rock: true, tip: 'the notebook as one drawing; its soft shadow stays real' },
    { sub: 'Crosshatch' },
    { k: 'rockBrush', l: 'Brush', t: 'select', o: BRUSHES, rock: true },
    { k: 'rockInk', l: 'Ink', t: 'color', rock: true },
    { k: 'rockWeight', l: 'Weight', t: 'range', min: 0.2, max: 3, step: 0.05, rock: true },
    { k: 'rockSpacing', l: 'Line spacing', t: 'range', min: 0.4, max: 2.5, step: 0.05, rock: true },
    { k: 'rockAngle', l: 'Angle offset °', t: 'range', min: -45, max: 45, step: 1, rock: true },
    { k: 'rockRand', l: 'Wobble', t: 'range', min: 0, max: 1, step: 0.05, rock: true },
    { k: 'rockBands', l: 'Tonal layers', t: 'range', min: 1, max: 4, step: 1, rock: true, tip: 'each darker tone adds a hatch layer at a new angle' },
    { k: 'rockBody', l: 'Paper body', t: 'range', min: 0, max: 1, step: 0.05, rock: true },
    { sub: 'Book shadow (drawn)' },
    { k: 'shadowOn', l: 'Shadow', t: 'bool', rock: true },
    { k: 'shadowStrength', l: 'Strength', t: 'range', min: 0, max: 1, step: 0.02, rock: true },
    { k: 'shadowX', l: 'Offset x', t: 'range', min: -120, max: 120, step: 1, rock: true },
    { k: 'shadowY', l: 'Offset y', t: 'range', min: -120, max: 120, step: 1, rock: true },
    { k: 'shadowSpread', l: 'Spread', t: 'range', min: 0.6, max: 1.8, step: 0.02, rock: true },
    { k: 'shadowSpacing', l: 'Line spacing', t: 'range', min: 0.4, max: 2.5, step: 0.05, rock: true },
    { k: 'shadowAngle', l: 'Angle °', t: 'range', min: -90, max: 90, step: 1, rock: true },
    { sub: 'Spotlight reveal (hover)' },
    { k: 'spotRadius', l: 'Radius px', t: 'range', min: 20, max: 500, step: 5 },
    { k: 'spotFeather', l: 'Soft edge px', t: 'range', min: 0, max: 300, step: 5 },
    { k: 'spotDissolve', l: 'Dissolve', t: 'range', min: 0, max: 2, step: 0.05, tip: 'noise eats the edge instead of a clean circle' },
    { k: 'spotSpeed', l: 'Fade speed', t: 'range', min: 0.5, max: 12, step: 0.5 },
  ],
  water: [
    { k: 'waterOn', l: 'Water', t: 'bool' },
    { sub: 'Sources — what makes ripples' },
    { k: 'rippleFishPct', l: 'Fish that ripple %', t: 'range', min: 0, max: 100, step: 1, tip: 'share of the school whose tail beats touch the surface' },
    { k: 'rippleBeat', l: 'Tail-beat strength', t: 'range', min: 0, max: 3, step: 0.05 },
    { k: 'rippleSurfacing', l: 'Surfacing chance %/s', t: 'range', min: 0, max: 30, step: 0.5, tip: 'a rippling fish occasionally runs along the surface for ~2 s, leaving rings' },
    { k: 'rippleTouch', l: 'Touch strength', t: 'range', min: 0, max: 3, step: 0.1, tip: 'click or drag the pond' },
    { sub: 'Physics' },
    { k: 'rippleDetail', l: 'Grid px (finer ↔ coarser)', t: 'range', min: 4, max: 16, step: 1, water: true },
    { k: 'rippleLife', l: 'Ripple life', t: 'range', min: 0, max: 1, step: 0.02, damp: true, tip: '0 = fades in a second, 1 = keeps ringing' },
    { k: 'rippleSpeed', l: 'Wave speed', t: 'range', min: 10, max: 60, step: 1, tip: 'simulation steps per second' },
    { sub: 'Ink lines — one line per wavefront' },
    { k: 'inkColor', l: 'Colour', t: 'color' },
    { k: 'inkBrush', l: 'Brush', t: 'select', o: BRUSHES },
    { k: 'inkWeight', l: 'Weight', t: 'range', min: 0.2, max: 3, step: 0.05 },
    { k: 'inkOpacity', l: 'Opacity', t: 'range', min: 0, max: 1, step: 0.02 },
    { k: 'inkDetail', l: 'Detail', t: 'range', min: 0, max: 1, step: 0.02, tip: 'higher draws fainter ripples too' },
    { k: 'inkStrokes', l: 'Max lines', t: 'range', min: 5, max: 300, step: 5 },
    { k: 'inkPenSpeed', l: 'Pen speed px/s', t: 'range', min: 50, max: 2000, step: 10, tip: 'how fast each line draws itself' },
    { k: 'inkLife', l: 'Line life s', t: 'range', min: 0.3, max: 8, step: 0.1, tip: 'stays for ~half, fades for the rest' },
    { k: 'inkEvery', l: 'New lines every ms', t: 'range', min: 100, max: 2000, step: 50 },
    { sub: 'Pond wash' },
    { k: 'pondOn', l: 'Pond wash', t: 'bool', pond: true },
    { k: 'pondColor', l: 'Colour', t: 'color', pond: true },
    { k: 'pondOpacity', l: 'Opacity', t: 'range', min: 0, max: 1, step: 0.02 },
    { k: 'pondFlow', l: 'Movement', t: 'range', min: 0, max: 1, step: 0.02, tip: 'drift and swirl speed together' },
    { k: 'pondSwirl', l: 'Swirl amount', t: 'range', min: 0, max: 80, step: 1 },
    { k: 'pondSwirlSize', l: 'Swirl size', t: 'range', min: 0.2, max: 3, step: 0.05, tip: 'bigger = smaller, busier swirls' },
    { k: 'pondBreathe', l: 'Breathe', t: 'range', min: 0, max: 1, step: 0.02 },
  ],
  visitors: [
    { k: 'visitorsOn', l: 'Leave a fish', t: 'bool', visitors: true, tip: 'show the card visitors design a fish with' },
    { k: 'visitorCap', l: 'Pond capacity', t: 'range', min: 1, max: 60, step: 1, visitors: true, tip: 'the pond keeps this many visitor fish; the oldest swims on when a new one arrives' },
    { k: 'visitorHover', l: 'Names on hover', t: 'bool' },
  ],
  tank: [
    { k: 'paper', l: 'Paper', t: 'color' },
    { k: 'blend', l: 'Blend', t: 'select', o: ['source-over', 'multiply'] },
    { k: 'alphaNear', l: 'Opacity, large', t: 'range', min: 0, max: 1, step: 0.02 },
    { k: 'alphaFar', l: 'Opacity, small', t: 'range', min: 0, max: 1, step: 0.02 },
    { k: 'mouse', l: 'Pointer is', t: 'select', o: ['flee', 'attract', 'none'] },
    { k: 'mouseRadius', l: 'Pointer radius', t: 'range', min: 20, max: 500, step: 10 },
    { k: 'showAtlas', l: 'Show atlas', t: 'bool' },
  ],
};


/** key → side-effect flags, derived from SCHEMA (paint, water, pond, damp, journal, rock, visitors, book) */
export var FLAGS = {};
Object.keys(SCHEMA).forEach(function (g) { SCHEMA[g].forEach(function (c) { if (c.k) FLAGS[c.k] = c; }); });
